on: push
name: check_knit
jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check
      run:  Rscript -e "rmarkdown::render('hw1.Rmd')"
      
